///  <reference types="Cypress" /> 


it('Replenishment', () => {
      cy.viewport(1800, 700)
      cy.visit('https://test.buildgcp.com/login')
      .get('[name="login"]')
      .type('test-user')
      .get('[name="password"]')
      .type('aA123123!')
      .get('.MuiButtonBase-root')
      .click()
      .wait(5000)
      // .get('a[href="/projects"]')
      // .click()
      // .get('.MuiButton-label')
      // .click()
      // .get('input[name="name"]')
      // .type('AutotestCypress')
      // .should('have.value', 'AutotestCypress')
      // .end('be.visible')
      .visit('https://test.buildgcp.com/database/categories?m=add')
      .get('label[class="MuiFormLabel-root MuiInputLabel-root MuiInputLabel-formControl MuiInputLabel-animated MuiInputLabel-filled"]')
      .should('contain.text', 'Category Name *')
})
      it.only('Money transfer between foreign card', () => {
      cy.viewport(1800, 700)
      cy.visit('https://next.privat24.ua/money-transfer/card?lang=en')
      .get('input[data-qa-node="numberdebitSource"]')
      .type('4552331448138217')
      .get('input[data-qa-node="expiredebitSource"]')
      .type('0524')
      .get('input[data-qa-node="cvvdebitSource"]')
      .type('111')
      .get('input[data-qa-node="firstNamedebitSource"]')
      .type('Shayne')
      .get('input[data-qa-node="lastNamedebitSource"]')
      .type('McConnelly')
      .get('input[data-qa-node="numberreceiver"]')
      .type('5309233034765085')
      .get('input[data-qa-node="firstNamereceiver"]')
      .type('Juliana')
      .get('input[data-qa-node="lastNamereceiver"]')
      .type('Janssen')
      .get('input[data-qa-value="200"]')
      .type('300')
      .get('span[data-qa-node="toggle-comment"]')
      .click()
      .get('textarea[data-qa-node="comment"]')
      .type('Cypress test')
      .get('button[type="submit"]')
      .wait(2000)
      .click()
      .get('span[data-qa-node="payer-card"]')
      .should('have.text', '* 8217')
      .get('span[data-qa-node="receiver-card"]')
      .should('have.text', '* 5085')
      .get('div[data-qa-node="receiver-amount"]')
      .should('have.text', '300 UAH')
      .get('div[data-qa-value="88.63 UAH"]')
      .should('have.text', '88.63 UAH')
      .get('[data-qa-node="total"]')
      .find('span')
      .should('contain.text', '388.63')
      .get('[data-qa-node="total"]')
      .find('small')
      .should('contain.text', 'UAH')


})