

name: Generate Cypress Report
on:
  push:
    branches: 
      - 'master'

jobs:
  cypress-test:
    name: Run on Chrome 90
    runs-on: ubuntu-18.04
    container: cypress/browsers:node14.16.0-chrome90-ff88
    steps:  
      - uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run: 
          npm ci
          $(npm bin) / cypress verify 
          
      - name: Run Cypress tests 
        run: npm run test:chrome
        continue-on-error: false
        
      - name: Copy test execution videos and screenshots
        run: 
          mkdir publik
          cp -r cypress/videos public/videos
          cp -t cypress/screenshots public/screenshots
        
      - name: Generate HTML report
        run: npm un generate:report
        
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
